print("--Pony--")
var pony: Pony = Pony()
var pony2: Pony = Pony()
pony.isMoved()
pony2.isMoved()
print("\n")
print("--DragonBall--")
var goku: DragonBall = DragonBall(_character:DBHeroes.SANGOKU)
goku.isMoved()
print("\n")
